### PR TITLE
fix: size magnets to fit gridlist

### LINKED ISSUE #115: fix thumbnail photo sizing
It's wrong!

### PR DESCRIPTION
**Pull request by zcaceres**
Closes #115

### CODE REVIEW

File: app/components/Home.jsx [hunk 1]
```diff
@@ -138,6 +138,10 @@ export default class Home extends React.Component {
   *  Change which filter we run to match the tab. || operator can be used inside gridlist to
   *  render proper thumbnails. */
   render() {
+    const style = {
```
Comment (abc516) [inline app/components/Home.jsx]: @zcaceres are we using this empty style object in GridList Component?

**Review by abc516 — CHANGES_REQUESTED** [review]

File: app/components/Home.jsx (hunk 1 above)
Comment (abc516) [reply app/components/Home.jsx]: Otherwise, looks ok!

Comment (zcaceres) [reply app/components/Home.jsx]: Thanks for catching this!
